name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Build
      id: step1
      run: cargo build --verbose
    - name: Run tests
      id: step2
      run: cargo test --verbose
    - name: Install Tools
      id: step3
      run: cargo install wasm-pack
    - name: Wasm build
      id: step4
      run: wasm-pack build
    - name: Move pkg to gh-page
      id: step5
      run: mv ./pkg ./public/pkg 
    - name: GitHub Pages action
      id: step6
      uses: peaceiris/actions-gh-pages@v3.6.1
        
