name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Install Tools
      run: cargo install wasm-pack
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run wasm
      run: wasm-pack build
    - name: Move pkg to gh-page
      run: mv ./pkg ./public/pkg 
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
        
