name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Build
      id: step1
      run: cargo build --verbose
    - name: Run tests
      id: step2
      run: cargo test --verbose
    - name: Install Tools
      id: step3
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Wasm build
      id: step4
      run: wasm-pack build --release -d public
    - name: Remove gitignore in pkg
      id: step5
      run: sudo rm -rf pkg/.gitignore
    - name: Move pkg to gh-page
      id: step6
      run: mv ./pkg ./public/pkg 
    - name: GitHub Pages action
      id: step7
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
